### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by Ledragon** [CalebBell/thermo#101]
Hi,
Thanks for the library. I used it in the past, and it worked well; however, I cannot manage to get the latest version to install, due to long paths (or at least that's the hint I get). This seems to be coming from the docs folder, in particular sub-folder "Examples/Chemical Thermodynamics for Process Simulation", that contains pretty long file names.
I tried using a different temp path (such as c:\piptmp), but paths still seem too long...

```
Collecting thermo
  Using cached thermo-0.2.14.tar.gz (11.6 MB)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\hugues.stefanski\\AppData\\Local\\Temp\\pip-install-6lzv2ycm\\thermo_b8140f90748b4996a7b2b92af1254633\\docs/Examples/Chemical Thermodynamics for Process Simulation/Problem 14.05 Required Power for R134a Compression Using a High Precision Equation of State.ipynb'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths
```

Not sure what an ideal solution would be, either to exclude the examples when installing with pip (maybe n,ot desirable), or reduce file names?

**Edit**: I managed to install version 0.2.13 without any problem

**Comment by CalebBell** [comment]
Hi,
I have stopped shipping the docs as of the new release 0.2.16. Can you confirm the error is no longer present?
Sincerely,
Caleb

**Comment by Ledragon** [comment]
Hi,
Confirmed, it works. Thanks for the quick fix!
Hugues
