### ISSUE TITLE
Need ability to flash with extra heat capacity (e.g. from catalyst or reactor mass)

### ISSUE THREAD

**Issue by alexchandel** [CalebBell/thermo#105]
`FlashVL` supports flashing to a given `H`.  But often (for example flashing after adding ∆H<sub>rxn</sub>), one needs to add some additional heat capacity, for example from the catalyst or reactor mass.

But there's no mechanism to add extra substances that don't participate VLE (e.g. solids in thermal equilibrium).

A partial workaround is to multiply the ∆H by `cp0 / (cp0 + extra_cp)`, where `cp0 = current_eq.dH_dT_P()`.  But this is inaccurate if `dH_dT_P()` changes between the initial and final H.

Is it possible to flash with such extra substances in the existing API?  If not, could you add it?

**Comment by CalebBell** [comment]
I don't plan to do this work, so I am closing this issue.
