### ISSUE TITLE
Need example/method for Txy, Pxy, and xy diagrams for binary systems

### ISSUE THREAD

**Issue by alexchandel** [CalebBell/thermo#109]
Txy, Pxy, and xy diagrams are some of the simplest and most fundamental thermodynamic diagrams for characterizing a binary system, and something any thermo user (or student) would want to produce.

There are no examples of, or methods for, generating Txy, Pxy, or xy diagrams.  The closest is the [plot_TP method of Flash](https://thermo.readthedocs.io/thermo.flash.html#thermo.flash.Flash).

They were implemented once [here](https://github.com/CalebBell/thermo/commit/79280c43ce0226dcdb40cd2267c0a8a70b90e2b9), but this is now relegated to the [Legacy Property Packages](https://thermo.readthedocs.io/thermo.property_package.html) module.

**Comment by CalebBell** [comment]
Hi Alex,
I may be able to get to this. Two-component systems are essentially two phase, and the flash algorithms for that are pretty good. It is only near the critical point that issues occur, or at very low pressures. 

To improve the behavior and allow convergence near the critical point, I want to figure out and understand Dr. Ulrich Deiters and Dr. Ian Bell's paper on the topic:

Deiters, Ulrich K., and Ian H. Bell. “Calculation of Phase Envelopes of Fluid Mixtures through Parametric Marching.” AIChE Journal 0, no. 0 (n.d.): e16730. https://doi.org/10.1002/aic.16730.

I haven't made progress on understanding it so far, however. 

Caleb

**Comment by CalebBell** [comment]
This functionality is now implemented. Binary systems are shown with the Modified UNIFAC model for the liquid phase and Peng-Robinson for the vapor phase, [here](https://thermo.readthedocs.io/Examples/Creating%20Txy%2C%20Pxy%2C%20and%20xy%20diagrams%20for%20the%20binary%20water%20ethanol%20system%20with%20Modified%20UNIFAC%20%28Dortmund%29.html).
Phase envelope functionality for multicomponent systems also has an example, in this case the nitrogen-oxygen-argon system, [here](https://thermo.readthedocs.io/Examples/Creating%20Nitrogen%2C%20oxygen%2C%20and%20nitrogen%20ternary%20air%20system%20phase%20envelope.html).

Limited improvements to the convergence of bubble and dew points has been made in the mean time, as well.
