### ISSUE TITLE
Bug when calculating Liquid Heat Capacity 

### ISSUE THREAD

**Issue by eacanoz** [CalebBell/thermo#110]
Hello,

I was testing the module **thermo.mixture** to estimate thermodynamic properties for different mixtures. When calculating the Heat Capacity for a Water-Ethylene Glycol mixture, object return "None". When I check the calculated attributes, I saw that Cp and Cpl have the value of "None" eventhough the phase is liquid ('l'). Other parameters like Cpg and Cps are calculated normally.

![imagen](https://user-images.githubusercontent.com/103229639/162347119-e5bad00b-d5ce-4951-a9c2-93a0c5128f88.png)

**Comment by CalebBell** [comment]
Hi,
This regression was introduced about 15 months ago during some clean up. I have fixed the issue in thermo v0.2.20

```
Mixture(['water', 'ethylene glycol'], zs=[.5, .5], T=300, P=1e5).Cpl
2803.778714115564
```
