### ISSUE TITLE
Gas phase mixture enthalpy values decreasing with increased pressure

### ISSUE THREAD

**Issue by OdhranOOC** [CalebBell/thermo#126]
Hi @CalebBell,

I was recently working with an air mixture in a thermodynamic system (calculating enthalpies, specific works, etc). I noticed that the gas phase enthalpy for an air mixture actually decreases with increased pressure. For example: 

```
from chemicals import normalize
from thermo import ChemicalConstantsPackage, CEOSGas, CEOSLiquid, PRMIXTranslatedConsistent, FlashVL
from thermo.interaction_parameters import IPDB
import numpy as np
import matplotlib.pyplot as plt

constants, properties = ChemicalConstantsPackage.from_IDs(['nitrogen', 'oxygen', 'argon'])
kijs = IPDB.get_ip_asymmetric_matrix('ChemSep PR', constants.CASs, 'kij')
eos_kwargs = {'Pcs': constants.Pcs, 'Tcs': constants.Tcs, 'omegas': constants.omegas, 'kijs': kijs}
gas = CEOSGas(PRMIXTranslatedConsistent, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
liquid = CEOSLiquid(PRMIXTranslatedConsistent, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
flasher = FlashVL(constants, properties, liquid=liquid, gas=gas)
zs = normalize([78.08, 20.95, .93])

x = np.linspace(500000,20000000, 100)
gas_H = np.zeros_like(x)

k=0
for i in x:
    # print("i = ", i)
    gas_H[k] = flasher.flash(T=500, P=i, zs=zs, retry=True).H()
    k=k+1

plt.figure()
plt.plot(x,gas_H, label = "gas_H")
plt.xlabel("Pressure")
plt.ylabel("Enthalpy")
plt.legend()
plt.show()
```

<img width="638" alt="Screenshot 2022-09-01 at 09 54 25" src="https://user-images.githubusercontent.com/64638908/187874274-fb4ea603-1efc-485a-8dbf-914927ecb2fa.png">

Is there possibly an alternative approach that would not show this behaviour? Unless I'm mistaken and this behaviour is actually correct?

Thanks and Regards,
Odhran

**Comment by OdhranOOC** [comment]
Much appreciated Caleb! Ah interesting I did read that Lemmon paper a few years back actually. So can I swap out the current gas phase EOS then for the improved Lemmon one, and leave the liquid phase as it is? How would that look? 

**My current code for reference:** 
```
constants, properties = ChemicalConstantsPackage.from_IDs(['nitrogen', 'oxygen', 'argon'])
kijs = IPDB.get_ip_asymmetric_matrix('ChemSep PR', constants.CASs, 'kij')
eos_kwargs = {'Pcs': constants.Pcs, 'Tcs': constants.Tcs, 'omegas': constants.omegas, 'kijs': kijs}
gas = CEOSGas(PRMIXTranslatedConsistent, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
liquid = CEOSLiquid(PRMIXTranslatedConsistent, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
flasher = FlashVL(constants, properties, liquid=liquid, gas=gas)
zs = normalize([78.08, 20.95, .93])
```

Also, do you know if the Lemmon model is faster than the alternative I have above, or is it actually slower due to the increased accuracy? 

Much appreciated

**Comment by CalebBell** [comment]
Hi Odhran,
Unfortunately the Lemmon model is pseudo-pure, i.e. incapable of participating in vapor-liquid equilibrium. In thermo, you can only use it for obtaining vapor properties. Adding a liquid phase would not work with it. Additionally, it is slower due to its complexity. 
Sincerely,
Caleb
