### ISSUE TITLE
Data for CAS# 64742-48-9 (Petroleum Naptha) missing

### ISSUE THREAD

**Issue by kgkeshav15** [CalebBell/thermo#128]
Hi,
The search for this CAS # 64742-48-9  gives following error: 
"A valid CAS number (64742-48-9) was recognized, but is not in the database"

Can any Data be added by the normal users? If so, I would gladly like to contribute and add data.

Thank you very much in advance for your quick reply.

**Comment by CalebBell** [comment]
Hi kgkeshav15,
Data is only available for pure species. Naptha is not a real chemical; it is a complicated mixture. Usually oil characterization tools are used to deal with those types of components, but you need to know things like the boiling point and density before you can even get started. There isn't one Naptha which is truly representative. Sorry.

Having said that, I am experimenting with downloading data from wikidata in the `chemicals` project. If data were submitted and that CAS number was in the database, I could theoretically make the data available in an update. See an example chemcial: https://www.wikidata.org/wiki/Q15779

Caleb

**Comment by kgkeshav15** [comment]
Hi Caleb,
Which data is required? I have an access to Perry's Handbook in which the data could be found. I can give to you to add in the database. 
Regards,
Kgkeshav15

**Comment by CalebBell** [comment]
Hi Kgkeshav15,
It would require at least:
Formula
Critical temperature
critical pressure
critical volume
acentric factor

Generally these are helpful too:
Melting point
boiling point
Heat of vaporization
Heat of fusion

You will also have to figure out how to make the wikidata page, and add the data.

**Comment by kgkeshav15** [comment]
Sorry Buddy, Cannot find this data in the perry’s.It is itself a mixture of multiple pure chemicals, and there are many trade mixtures.    Gesendet von Mail für Windows Von: Caleb BellGesendet: Sonntag, 13. November 2022 17:56An: CalebBell/thermoCc: kgkeshav15; AuthorBetreff: Re: [CalebBell/thermo] Data for CAS# 64742-48-9 (Petroleum Naptha) missing (Issue #128) Hi Kgkeshav15,It would require at least:FormulaCritical temperaturecritical pressurecritical volumeacentric factorGenerally these are helpful too:Melting pointboiling pointHeat of vaporizationHeat of fusionYou will also have to figure out how to make the wikidata page, and add the data.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
