### ISSUE TITLE
Thermodynamic Properties of Solutions

### ISSUE THREAD

**Issue by jd4900** [CalebBell/thermo#13]
First @CalebBell i'd like to thank you for this software. It's a life-saver! 

How difficult would it be to update the Laliberte2009.tsv file with Glucose, Fructose and some other simple sugars? I realize that sucrose is added and that is currently what I am using but I would like to find out how much glucose and fructose there are seperately. Im not sure what the process is for adding other electrolytes or if you have a script that calculates the fitting parameters based off of some data. 

I am looking at modelling glucose/fructose/ethanol/water systems and finding the density for a given concentration or more accurately use optimization to estimate the amount of glucose/fructose given a density.

**Comment by CalebBell** [comment]
Hi Joshua!
Thanks. I'm glad it's been helpful to you. 

The Laliberte model was actually developed for electrolytes, and sucrose and ethanol were added only to prove the model could work for organic substances. The parameters were developed by Laliberte, not me, though different data files could be shipped with thermo as well. I don't have any script for fitting data or easily adding it to thermo. A bare minimum would be another line in the file with the parameters included. 
I don't think there's anything special about fitting; just some temperature and water-fraction dependent data covering the rage of interest.

From your description, though, you're facing a degree-of-freedom problem. Unless you have other relationships in your model like a reaction, I don't see how you can relate one density value with four concentrations.

Cheers,
Caleb

**Comment by jd4900** [comment]
Is there a paper or something where I can find these parameters for Glucose and Fructose or how I can generate them? I am just confused as to what a 0 to 5 or v 0 to 5 actually represent in terms of thermodynamics. 

Once I generate or find the parameters I can add them to the dictionary and submit a pull request.  

I have a reaction as well as well defined bounds that I am working with. The degree-of-freedom checks out once I factor in my knowledge about the system.

**Comment by CalebBell** [comment]
Glad to hear you've got your system figured out! This density problem is definitely doable. 

The c0-5 parameters are needed for density, the v parameters are for viscosity. You can see the equation for density here: https://thermo.readthedocs.io/en/latest/thermo.electrochem.html#thermo.electrochem.Laliberte_density_i The main paper is:
Laliberte, Marc. “A Model for Calculating the Heat Capacity of Aqueous Solutions, with Updated Density and Viscosity Data.” Journal of Chemical & Engineering Data 54, no. 6 (June 11, 2009): 1725-60. doi:10.1021/je8008123 https://pubs.acs.org/doi/abs/10.1021/je8008123

I think the only parameters that would be needed are: CASRN	Formula	MW	c_0	c_1	c_2	c_3	c_4	Min T	Max T	Max w	No of points in corr

Let me know if you have any questions about fitting!

**Comment by yfq000** [comment]
This software is very useful to me, thank you for sharing.
I have two questions that need help.
How to calculate the specific enthalphy of water at current temperature and pressure? For example, I know that the specific enthalphy of water at 500K and 1E6Pa is 2891kJ/kg.
How to calculate the saturation temperature of water at a specific temperature，and how to calculate the saturation pressure of water at a specific temperature?
