### ISSUE TITLE
Mixture diffusion coefficient

### ISSUE THREAD

**Issue by tbridel** [CalebBell/thermo#130]
Good morning everyone,

In an application I am building around `thermo`, I would need to compute the Lewis number of a n-components mixture - so basically my understanding for a mixture is that we can think in bulk as a first approximation and go for the following expression:

```
Le = thermal_conductivity / (rho_mass * mean_diffusion_coefficient * specific_cp).
```

I am using `flash` as per the recommendations found in the docs, so I find myself with an `EquilibriumState` but I can't figure out how to compute a mean diffusion coefficient for the mixture.
Can you please advise ?

Thank you in advance !
- Thibault

**Comment by CalebBell** [comment]
Hi Thibault,
Diffusion is not a feature supported by the Thermo library at this time, sorry.  I'll let you know if it's added at some point.
Cheers,
Caleb
