### ISSUE TITLE
air.lemmon2000_rho

### ISSUE THREAD

**Issue by gamafreire** [CalebBell/thermo#134]
Dear @CalebBell,
I hope this message finds you well. I have been encountering an issue with air density.
Here I am again, giving you work.

```
from chemicals import air
print(
    air.lemmon2000_rho( T=293.15, P=101325),
    air.lemmon2000_air_MW/24.06)
```

`Output: 41.58660634055702 1.2035993349958438`

thermo.version
'0.2.23'

Thank you very much for your time and support. I look forward to your guidance and getting this resolved.

Best regards,
Filipe Gama Freire

**Comment by CalebBell** [comment]
What seems to be the issue? The units of lemmon2000_rho are clearly documented as mol/m^3; if you are looking for kg/m^3 you can do

```
>>> from chemicals import *
>>> Vm_to_rho(1/lemmon2000_rho( T=293.15, P=101325), lemmon2000_air_MW)
1.2042898983736545
```

**Comment by gamafreire** [comment]
Dear @CalebBell,
Thank you!
Sorry for bothering you againFilipe
