### ISSUE TITLE
Issues for Zg calculation

### ISSUE THREAD

**Issue by Great0102** [CalebBell/thermo#139]
If we want to calculate the compressibility factor of the chemical in the gas phase at the current temperature and pressure, Zg，following example is provided in the ducument.

>>>>>>Chemical('sulfur hexafluoride', T=700, P=1E9).Zg
>>>>>>11.4

However, after we calculate using this example, the results is 1. 

>>>>>>Chemical('sulfur hexafluoride', T=700, P=1E9).Zg
>>>>>>1

Actually, no matter what we input for the temperature and pressure, the results is always 1.

I also try to use another gas, such as methane, hydrogen, etc., the results is also 1.

Can you help to solve this problem?

**Comment by CalebBell** [comment]
Hello,
Please see the discussion here:
https://github.com/CalebBell/chemicals/issues/47
In general I strongly recommend the new flash-based methods.
