### ISSUE TITLE
Incompatibility with new SciPy release 1.14.0

### ISSUE THREAD

**Issue by tefavidal** [CalebBell/thermo#150]
The new release of SciPy 1.14.0 removed `interp2d`, which causes `thermal_conductivity.py` to crash. 

For details on the transition see https://scipy.github.io/devdocs/tutorial/interpolate/interp_transition_guide.html

**Comment by CalebBell** [comment]
Hi tefavidal,
I recognize this was an issue. The use wasn't in a super commonly used place, although obviously the tests would fail. I have updated the interpolation routine as well as other things that needed upgrading, and released thermo 0.3.0 with the updates today.
Sincerely,
Caleb
