### ISSUE TITLE
Z_g does not compute for Neon, Helium, Deuterium.

### ISSUE THREAD

**Issue by AndrewPrice775** [CalebBell/thermo#155]
I ran a test comparing Z_g outputs on each EOS for various gases. 

I use the following PC, TC, Omega inputs. Which yields an error, for example: 'SRKTranslatedConsistent' object has no attribute 'Z_g'
Note that Hydrogen Z output works on PR EOS, but not on VDW or RK methods.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/aprice/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/aprice/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

Gas Name | Pressure [Torr] | Temperature [K] | Pc [bar] | Tc [K] | Acentric Factor
-- | -- | -- | -- | -- | --
Helium | 200 | 298.15 | 2.2832 | 5.1953 | -0.3836
Hydrogen | 200 | 298.15 | 12.964 | 33.145 | -0.219
Neon | 200 | 298.15 | 26.6163 | 44.4 | -0.0355
Deuterium | 200 | 298.15 | 16.796 | 38.34 | -0.136

</body>

</html>

**Comment by CalebBell** [comment]
Hi Andrew,
Vapor/liquid designations are arbitrary past the supercritical point. The phase id algorithm used by the EOS object is documented here: https://chemicals.readthedocs.io/chemicals.utils.html#chemicals.utils.phase_identification_parameter
The EOS objects themselves are low level and I stand by the decision to use PIP for phase ID there.
If you use the Phase/Flash infrastructure, you can configure a Phase ID method in the BulkSettings object.
https://thermo.readthedocs.io/tutorial_phases_and_flash.html
https://thermo.readthedocs.io/thermo.bulk.html?highlight=BulkSettings#thermo.bulk.BulkSettings
Sincerely,
Caleb

**Comment by AndrewPrice775** [comment]
Hi Caleb,

Thank you for the response. Should I be calling eos.Z rather than Z_g?

**Comment by CalebBell** [comment]
Hi Andrew,
The raw EOS object doesn't provide that abstraction. The Phase and Bulk objects does provide a .Z() method though; I agree from a user's perspective you really... just want the property, not to think about what phase it is.
Caleb

**Comment by AndrewPrice775** [comment]
Hi Caleb,

Okay I see now. Let me work with Phase/Flash for a bit and see if I can get that to work for those super critical phases. Otherwise I'll return Z of 1 in my code. 
Thank you for your help.
