### ISSUE TITLE
EquilibriumState: nu / mu of phase

### ISSUE THREAD

**Issue by cloasdata** [CalebBell/thermo#159]
Hello Caleb,

long time no see, I hope you are well up.

Not sure but this should work? Or at least not raise an exception:
I could not dive deeper as I'm unable to locate the problem as eq.mu is magical added to the object. 

cheers simon

CEOSLiquid(eos_class=PRMIX, eos_kwargs={"Tcs": [190.564], "Pcs": [4599200.0], "omegas": [0.01142], "kijs": [[0.0]]}, HeatCapacityGases=[HeatCapacityGas(CASRN="74-82-8", MW=16.04246, similarity_variable=0.3116728980468083, extrapolation="linear", method="HEOS_FIT", tabular_data={'VDI_TABULAR': ([111.67, 120.0, 130.0, 140.0, 150.0, 160.0, 170.0, 180.0, 185.0, 190.0], [34.68379852, 36.78536078, 38.83879566, 41.88686306, 46.65147368, 54.84917074, 71.53332914, 121.50559204, 217.00635642, 2258.9387926]), 'JANAF': ([0.0, 100.0, 200.0, 250.0, 298.15, 300.0, 350.0, 400.0, 450.0, 500.0, 600.0, 700.0, 800.0, 900.0, 1000.0, 1100.0, 1200.0, 1300.0, 1400.0, 1500.0, 1600.0, 1700.0, 1800.0, 1900.0, 2000.0, 2100.0, 2200.0, 2300.0, 2400.0, 2500.0, 2600.0, 2700.0, 2800.0, 2900.0, 3000.0, 3100.0, 3200.0, 3300.0, 3400.0, 3500.0, 3600.0, 3700.0, 3800.0, 3900.0, 4000.0, 4100.0, 4200.0, 4300.0, 4400.0, 4500.0, 4600.0, 4700.0, 4800.0, 4900.0, 5000.0, 5100.0, 5200.0, 5300.0, 5400.0, 5500.0, 5600.0, 5700.0, 5800.0, 5900.0, 6000.0], [0.0, 33.258, 33.473, 34.216, 35.639, 35.708, 37.874, 40.5, 43.374, 46.342, 52.227, 57.794, 62.932, 67.601, 71.795, 75.529, 78.833, 81.744, 84.305, 86.556, 88.537, 90.283, 91.824, 93.188, 94.399, 95.477, 96.439, 97.301, 98.075, 98.772, 99.401, 99.971, 100.489, 100.96, 101.389, 101.782, 102.143, 102.474, 102.778, 103.06, 103.319, 103.56, 103.783, 103.99, 104.183, 104.363, 104.531, 104.688, 104.834, 104.972, 105.101, 105.223, 105.337, 105.445, 105.546, 105.642, 105.733, 105.818, 105.899, 105.976, 106.049, 106.118, 106.184, 106.247, 106.306])})], T=1.0, P=1.0, zs=(1.0,))
eq.nu(phase)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.2.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<input>", line 1, in <module>
TypeError: _make_getter_bulk_props.<locals>.get_bulk_prop() takes 1 positional argument but 2 were given
eq.nu(phase=phase)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.2.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<input>", line 1, in <module>
TypeError: _make_getter_bulk_props.<locals>.get_bulk_prop() got an unexpected keyword argument 'phase'

**Comment by cloasdata** [comment]
Hi Caleb,

Here is an minimum example. Looks like it occurs with any state. 
The example is decuced from how we build the flasher and flash to the given state.
Maybe it is just an error from my side. 

```python
class TestViscosity:
    def test_bug(self):
        '''
        Looks like a bug.
        https://github.com/CalebBell/thermo/issues/159
        '''
        names = ['methane', 'ethane']
        constants, properties = ChemicalConstantsPackage.from_IDs(names)
        eos_kwargs = dict(Tcs=constants.Tcs, Pcs=constants.Pcs, omegas=constants.omegas)
        phase_model_gas = CEOSGas(PRMIX, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
        phase_model_liquid = CEOSLiquid(PRMIX, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
        flasher = FlashVL(constants, properties, phase_model_gas, phase_model_liquid)
        zs = [.5,.5]

        eq: EquilibriumState = flasher.flash(zs, 300, 5_000_000)
        assert eq.phase == 'V'
        bulk_mu = eq.mu()
        assert isinstance(bulk_mu, float) # works
        try:
            mu = eq.mu(flasher.phases[0]) # error
        except TypeError as e:
            assert e


        eq = flasher.flash(zs, 50, 500)
        assert eq.phase == 'L'
        try:
            mu = eq.mu(flasher.phases[0]) # error
        except TypeError as e:
            assert e

        eq1 = flasher.flash(zs, 1,1)
        assert eq.phase == 'L'
        try:
            mu = eq1.mu(flasher.phases[0]) # error
        except TypeError as e:
            assert e 
```

**Comment by cloasdata** [comment]
Hi Caleb,

I do also not understand for what reason there is a second dynamic added method.
```python
    def test_kinematic_viscosity_function(self):
        names = ['methane', 'ethane']
        constants, properties = ChemicalConstantsPackage.from_IDs(names)
        eos_kwargs = dict(Tcs=constants.Tcs, Pcs=constants.Pcs, omegas=constants.omegas)
        phase_model_gas = CEOSGas(PRMIX, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
        phase_model_liquid = CEOSLiquid(PRMIX, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
        flasher = FlashVL(constants, properties, phase_model_gas, phase_model_liquid)
        zs = [.5, .5]

        eq: EquilibriumState = flasher.flash(zs, 300, 5_000_000)
        assert eq.phase == 'V'
        expected_nu = eq.nu()
        nu = eq.kinematic_viscosity()
        assert nu == expected_nu
        assert eq.kinematic_viscosity is not eq.nu # this indeed clear. However, the repr shows that both pointing to the same root.
```

**Comment by CalebBell** [comment]
Hi Simon,

The reason the nu/mu methods don't accept a phase is because they weren't programmed to, as shown in the documentation.
https://thermo.readthedocs.io/thermo.equilibrium.html#thermo.equilibrium.EquilibriumState.mu

The phase argument some methods support was sort of an accident - it helped me develop faster in some cases to use that pattern, and then it was exposed in the documentation, so I documented it. Not all methods accept a Phase parameter and in the case of nu/mu, there wasn't any advantage to be gained so I didn't implement it.

**Comment by cloasdata** [comment]
Hi Caleb,

thanks for the explanation.

I understand the point and it is not a big deal to interact with the phase directly instead through eqs.
But it is quiet easy to misinterpret the interface at the moment.  

Simon

P. S.
Here is a snippet demonstrating what Caleb is suggesting

```python
    def test_viscosity_on_phase(self):
        '''
        Explanation to others on
        https://github.com/CalebBell/thermo/issues/159
        '''
        names = ['methane', 'ethane']
        constants, properties = ChemicalConstantsPackage.from_IDs(names)
        eos_kwargs = dict(Tcs=constants.Tcs, Pcs=constants.Pcs, omegas=constants.omegas)
        phase_model_gas = CEOSGas(PRMIX, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
        phase_model_liquid = CEOSLiquid(PRMIX, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
        flasher = FlashVL(constants, properties, phase_model_gas, phase_model_liquid)
        zs = [.5, .5]

        eq: EquilibriumState = flasher.flash(zs, 300, 5_000_000)
        # that's how we should do it by default
        assert eq.gas.mu()
        # if needed one also can do following
        eq: EquilibriumState = flasher.flash(zs, 300, 5_000_000)
        current_gas_phase,*_ = eq.phases
        assert current_gas_phase.mu()
        # the above allows a user to wrap the current phase object into anything else:
        class MyPhaseClass:
            current_phase = None
            def get_some_special_property_regardless_what_phase_and_lazy(self):
                return self.current_phase.rho_mass() * 100
        liquid_phase = MyPhaseClass()
        eq: EquilibriumState = flasher.flash(zs, 300, 5_000_000)
        liquid_phase.current_phase = eq.phases[0]
        # do other stuff
        # time to call the property
        assert liquid_phase.get_some_special_property_regardless_what_phase_and_lazy()
```
