### ISSUE TITLE
Question: Joule Thomson State Change

### ISSUE THREAD

**Issue by cloasdata** [CalebBell/thermo#160]
Hello Caleb,

for a while I'm asking myself what is the preferred way to have the flasher interface make a state change via Joule Thomson Effect.
It is a bit strange, that we need to calculate the temperature drop outside of thermo.

```python
from thermo import ChemicalConstantsPackage, CEOSGas, PRMIX, CEOSLiquid, FlashVL, EquilibriumState


class TestJouleThomson:
    def test_basic_path(self):
        names = ['methane', 'ethane']
        constants, properties = ChemicalConstantsPackage.from_IDs(names)
        eos_kwargs = dict(Tcs=constants.Tcs, Pcs=constants.Pcs, omegas=constants.omegas)
        phase_model_gas = CEOSGas(PRMIX, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
        phase_model_liquid = CEOSLiquid(PRMIX, eos_kwargs=eos_kwargs, HeatCapacityGases=properties.HeatCapacityGases)
        flasher = FlashVL(constants, properties, phase_model_gas, phase_model_liquid)
        zs = [.99, .01]
        start_temperature = 300
        start_pressure = 50*100000
        final_pressure = 30*100000
        eq: EquilibriumState = flasher.flash(zs, T=start_temperature, P=start_pressure)
        jt_koeff_at_start = eq.gas.Joule_Thomson()
        assert isinstance(jt_koeff_at_start, float)
        final_temperature = start_temperature - (start_pressure-final_pressure) * jt_koeff_at_start
        assert final_temperature < start_temperature
        eq_final = flasher.flash(zs, final_temperature, final_pressure)
        assert eq.gas.V() < eq_final.gas.V()
```

cheers simon

**Comment by CalebBell** [comment]
Hi Simon,
I don't have any context on what you are trying to do, but conventionally if you want to know the temperature change from an isenthalpic pressure change you do a PH flash with the new pressure following your previous PT conditions. JT coefficient refers only to a property at specific conditions and the multiplication you are doing is only accurate over short ranges.
Sincerely,
Caleb

**Comment by cloasdata** [comment]
Thanks for answering. I finally found the answer also in the examples.... 
https://thermo.readthedocs.io/Examples/Chemical%20Thermodynamics%20for%20Process%20Simulation/Example%2014.2%20Joule-Thomson%20Effect.html

The thing was, that we started earlier with the mixture interface and on to the way the flasher we oversee this simple solution.
