### ISSUE TITLE
Intizialize chemicals at given time

### ISSUE THREAD

**Issue by cloasdata** [CalebBell/thermo#161]
Hello Caleb,

is there a way to initialize the chemicals package at a given time. At the moment it looks like chemicals is init lazy. But this may or may not happen at a point, where we hang unnecessarily. So it would quiet nice to initialize when it does not impact user experience.

 Thanks Simon

**Comment by CalebBell** [comment]
Hi Simon,
There is no official functionality to do this. I wrote this function you may find useful but you will need to keep it up to date, it uses unofficial methods.
```
	def complete_lazy_loading():
		critical._load_critical_data()
		dipole._load_dipole_data()
		environment._load_GWP_ODP_data()
		environment._load_logP_data()
		heat_capacity._load_Cp_data()
		interface.load_interface_dfs()
		lennard_jones._load_LJ_data()
		miscdata._load_VDI_saturation_dict()
		miscdata._load_miscdata()
		permittivity._load_permittivity_data()
		phase_change._load_phase_change_constants()
		phase_change._load_phase_change_correlations()
		reaction._load_reaction_data()
		refractivity._load_RI_data()
		safety._load_safety_data()
		thermal_conductivity._load_k_data()
		triple._load_triple_data()
		vapor_pressure.load_vapor_pressure_dfs()
		viscosity._load_mu_data()
		volume._load_rho_data()
		molecular_geometry._load_RG_data()
		combustion._load_combustion_data()
		solubility._load_solubility_data()
		try:
			identifiers.search_chemical('asdfasddsaf', autoload=True, cache=False)
		except:
			pass
```
Make sure you pin the version of chemicals in your requirements.txt and expect this to break and require maintenance.
Sincerely,
Caleb
