### ISSUE TITLE
Documentation for solid phase in FlashPureVLS

### ISSUE THREAD

**Issue by danieljameshunt** [CalebBell/thermo#163]
FlashPureVLS takes in simple phase objects of CEOSLiquid and CEOSGas for liquid and gas phases. Solid object is consistently kept empty and does not appear to have a worked example, making it difficult to identify what to do if working with an element which can enter solid phase

**Comment by danieljameshunt** [comment]
Should add that the current goal is to generate a simple phase diagram for Ar vs temperature and pressure. Diagram not only does not contain solid phase (presumably an easy fix), but also gas phase does not seem to line up with current literature

**Comment by CalebBell** [comment]
Hi Dan,
I recommend you look elsewhere. Solid phases are currently not implemented.
Sincerely,
Caleb
