### ISSUE TITLE
Try to understand the reason for StreamArgs and EquilibriumStream

### ISSUE THREAD

**Issue by cloasdata** [CalebBell/thermo#164]
Hello Caleb,

I started to work with the stream classes which thermo provides, mainly because it frees us from implementing all the mixing stuff we need to consider. I think this also is a reason why thermo implements the stream class. 
But I do not understand the reason for having two classes doing the nearly the same thing. 
Can you please explain?

Thanks, Simon.

**Comment by CalebBell** [comment]
Hi Simon,
Please read the documentation and if needed message on [Gitter](https://app.gitter.im/#/room/#CalebBell_thermo:gitter.im) or email me if the information is not something you want public; this, like your last three "issues", are not bugs or inconsistencies or errors with the project. The `StreamArgs` counts specifications and provides a function to obtain an `EquilibriumStream` once enough specs have been set, and won't let you set conflicting specs. This is described by the [documentation clearly](https://thermo.readthedocs.io/thermo.stream.html#thermo.stream.StreamArgs).
Sincerely,
Caleb

**Comment by cloasdata** [comment]
Hi Caleb,

may I ask you do add the gitter channel to the project readme and docs. Until now I did not know about it. Sorry for bothering you here.
Regarding the "issue":
Following the documentation, it is somehow strange, that the StreamArgs requires a flasher for balance questions. I have seen the flasher satisfies the dependencies to MWs. But would it not be better, then to explicit but optional pass MWs to StreamArgs instead to pass a flasher. This would make StreamArgs more useable for question of balance. 

Simon
