### ISSUE TITLE
adding atoms labels to draw_3d function

### ISSUE THREAD

**Issue by gbrault** [CalebBell/thermo#22]
to [draw_3d](https://github.com/CalebBell/thermo/blob/3857ed023a3e64fd3039a32d53576c24990ef1c3/thermo/chemical.py#L634) function, add one variable, atomlabel, which defaults to true.
```
def draw_3d(self, width=300, height=500, style='stick', Hs=True, atomlabel=True):
```
then just before [p.zoomTo()](https://github.com/CalebBell/thermo/blob/3857ed023a3e64fd3039a32d53576c24990ef1c3/thermo/chemical.py#L668), add this code

```
            if atomlabel:
                p.addPropertyLabels("atom","","")
```
Atoms labels will then display, which is nice for people like me which are not chemical engineers!
This works with latest (python 3.7.3) conda installed version of thermo and py3Dmol from conda-forge.
![xylene](https://user-images.githubusercontent.com/7886676/59145511-4171bd80-89e5-11e9-8537-9ef7e0e179d6.png)

**Comment by CalebBell** [comment]
Hi Dr. Brault,

This looks like a good addition. Part of "The Zen of Python" is "Explicit is better than implicit"; so it's a very Pythonic addition! I'll try to get it into the next release of thermo!

Sincerely,
Caleb

**Comment by CalebBell** [comment]
Hi Gilbert,
This is added to the development version of thermo now. 
Sincerely,
Caleb

**Comment by gbrault** [comment]
Oh!, I had forget this one! Thanks Caleb!
