### ISSUE TITLE
how to define pseudo components ?

### ISSUE THREAD

**Issue by sivarammurugan** [CalebBell/thermo#23]
Is  there any way to define the pseudo components in thermo? By pseduo components,   I mean the petroleum cuts such as naphtha , gasoline , or c8 aromatics . Is there any way to define them  based on boiling point . How to obtain their thermodynamic properties ? I appreciate any help very much.

**Comment by ricardolira** [comment]
Hi,

I was wondering the same. If you have any information on the subject, please lmk.

Regards,

**Comment by CalebBell** [comment]
Hello,
I put together an example of using pseudo components with Thermo and doing a three-phase flash with the API SRK equation of state. It is available here: https://thermo.readthedocs.io/Examples/High%20Molecular%20Weight%20Petroleum%20Pseudocomponents.html

I hope it is helpful to you. I am closing the issue now.
Sincerely,
Caleb Bell
