### ISSUE TITLE
Saturation pressure (& temperature) for mixtures

### ISSUE THREAD

**Issue by kpkan** [CalebBell/thermo#24]
Dear @CalebBell ,

Thank you very much for such a great library! It makes my research work on PhD-thesis much easier!

I would like to ask you, if it is possible to calculate saturation temperature and pressure for binary mixtures using thermo? Are there any methods?
I tried to do it via 'eos_mix' module but it prints error (object has no attribute 'a') when I call 'Psat' method. I tried 'mixture' module, but it has corresponding methods for components only, but not for the mixture itself. 
Thank you in advance!

Best regards,
Pavel

**Comment by CalebBell** [comment]
Hi kpkan,

This functionality is available in the development version of thermo now. You can see some of the way it can be used in the following documents.

https://github.com/CalebBell/thermo/blob/master/docs/chemical_package_tutorial.rst
https://github.com/CalebBell/thermo/blob/master/docs/tutorial_phases_and_flash.rst
https://github.com/CalebBell/thermo/blob/master/thermo/phases.py

I don't know when this will be ready for release but you can install `thermo` from git not just pypi.

Sincerely,
Caleb
