### ISSUE TITLE
Data issue: CAS# 16949-15-8

### ISSUE THREAD

**Issue by ljn917** [CalebBell/thermo#28]
Hi,

It looks like the data for CAS# 16949-15-8 is not correct. As [this](http://www.commonchemistry.org/ChemicalDetail.aspx?ref=16949-15-8) shows, CAS# 16949-15-8 is LiBH4, but I got the following output. It looks like the hydrogens are dropped incorrectly.

```
>>> a=thermo.chemical.Chemical('16949-15-8')
>>> a.smiles
'[Li+].[B-]'
>>> a.rho
537.840616966581
```

Thanks

**Comment by alexchandel** [comment]
Problem is line 68158 of `chemical identifier.tsv`. PubChem [gave a mismatched formula, weight, & smiles](https://pubchem.ncbi.nlm.nih.gov/compound/20722760).  (Don't expect accuracy from the govt).  The smiles should be `[Li+].[BH4-]`.

**Comment by alexchandel** [comment]
It gets better.  PubChem has 5 separate "compound" entries, all claiming to be lithium borohydride:

1. https://pubchem.ncbi.nlm.nih.gov/compound/11996612 (non-existent)
2. https://pubchem.ncbi.nlm.nih.gov/compound/20722760 (non-existent)
3. https://pubchem.ncbi.nlm.nih.gov/compound/4148881
4. https://pubchem.ncbi.nlm.nih.gov/compound/139038538 (high-P polymorph)
5. https://pubchem.ncbi.nlm.nih.gov/compound/139046170 (high-P polymorph)

Wikipedia cites No.3, as does [the ChemSpider entry with the same CAS number](https://www.chemspider.com/Chemical-Structure.55732.html).

(There are also duplicated sodium aluminum hydride entries, one [showing net charge](https://pubchem.ncbi.nlm.nih.gov/compound/Sodium-aluminum-hydride) and the other [formal charge](https://pubchem.ncbi.nlm.nih.gov/compound/139046835).)

@CalebBell  I recommend deleting the CID# 20722760 row altogether, and adding a row for CID# 4148881 with the CAS# 16949-15-8.

Separately, given the number of errors & duplicates in PubChem, a `chemical identifiers duplicate.tsv` database should be created to alias the various duplicate CID's.

**Comment by CalebBell** [comment]
It has been quite some time but I have the scripts for adding/removing/editing chemical metadata working again (ported to python 3, working with new versions of pubchem & common chemistry integration)
I have resolved the issue. It is in the new chemicals release 1.3.1 and can be tested as follows:

	issue_28 = search_chemical('16949-15-8')
	assert issue_28.formula == 'BH4Li'
	assert issue_28.common_name == 'lithium borohydride'
	assert issue_28.pubchemid == 4148881
	
Sincerely,
Caleb
