### ISSUE TITLE
Multi component enthalpic curve calculation

### ISSUE THREAD

**Issue by lmg990** [CalebBell/thermo#36]
Hi,
I would like to generate enthalpic curves for a multi component mixture. 
1. My mixture is the mixing of a liquid flow and a gaz flow for which I know the composition, flow rate, temperature and pressure.
-> can I get the mixing temperature + the vapor ratio at a given pressure of these two flows ?
2. I managed to calculate the common properties and the latent heat for a set of températures and pressures with thermo.mixture but I need zs (mole fraction of all the components) as inlet parameters separately for the liquid part and for the gas part (they change with the temperature and pressure as the mixture is vaporized)
-> how can I calculate these zs from the composition of my mixture and the T, P ?
Last question : is it possible to evaluate the dew point of the mixture ?

If someone can drive me to a solution or even to a beginning of a track, it would be great…

Regards

**Comment by alexchandel** [comment]
You'll have to calculate the flash equilibrium point yourself, unless the undocumented and possibly broken [flash method](https://thermo.readthedocs.io/en/latest/thermo.property_package.html?highlight=dew_at_t#thermo.property_package.Property_Package.flash) of a property package class fits your needs (e.g. `UNIFAC_Dortmund_PP`).

The [Mixture class](https://thermo.readthedocs.io/en/latest/thermo.mixture.html) doesn't list a dew point method, but `.Pdew` works.  There's also [thermo.activity.dew_at_T](https://thermo.readthedocs.io/en/latest/thermo.activity.html?highlight=dew#thermo.activity.dew_at_T).  `Property_Package.Tdew` appears to be broken.

**Comment by lmg990** [comment]
Thanks Alex, I will take a look on all this...

**Comment by CalebBell** [comment]
Hi all,
Please see the new documentation. This is easy to do with the new flash interface.
Sincerely,
Caleb
