### ISSUE TITLE
python setup.py develop not working

### ISSUE THREAD

**Issue by Shimwell** [CalebBell/thermo#39]
Just wanted to put this out there in case anyone else wants to install the package using "develop" mode which is useful when making changes to the source code and not having to reinstall it to see the impact on the package.

`python setup.py develop `

currently returns an error 

![Screenshot from 2020-02-14 10-26-24](https://user-images.githubusercontent.com/8583900/74523163-8060f700-4f14-11ea-8859-3c3f3f3735d3.png)

There is an easy to fix if you want to use it in this way.

In setup.py replace the line

`from distutils.core import setup`

with

`from setuptools import setup`

This is the recommended solution for another package with the same issue from https://github.com/django-extensions/django-extensions/issues/92#issuecomment-946641

**Comment by CalebBell** [comment]
Hi Jonathan,
Thanks for the tip! I didn't know about that feature. I have merged the change into master.
A new release is available on PyPi with your fixes as well!

Sincerely,
Caleb
