### ISSUE TITLE
request for updated pypi package

### ISSUE THREAD

**Issue by DeclanMorbey** [CalebBell/thermo#40]
The last release of thermo via the PyPi package manager pip was back in 2017 but I notice there have been another 15 or so commits since then.

Any chance the package on the pypi repository can be updated?

**Comment by CalebBell** [comment]
Hi Declan,
Thanks for pointing that out. The CI infrastructure was failing as well. It was never my intent not keep pypi updated, it just happened. I have remedied the situation and pushed out thermo v0.1.40! 
Sincerely,
Caleb
