### ISSUE TITLE
Data Issue CAS 13465-78-6

### ISSUE THREAD

**Issue by serge-suvorov** [CalebBell/thermo#43]
Hi, how can i fix data issue for chlorosilane's atoms and MW?
Actual chemical formula is SiH3Cl, but I got
>>>Chemical('13465-78-6').atoms
{'Cl': 1, 'Si': 1}
it should be {'Cl': 1, 'Si': 1, 'H': 3}
>>>Chemical('13465-78-6').MW
63.5385
but it should be 66.56 (three hydrogens are lost)
>>>Chemical('13465-78-6').Tb
242.75
this is right

And another question. What is the best way to inject missing property to `thermo`?
Is this the right way?
>>>Chemical('13465-78-6').H_ref = value

**Comment by CalebBell** [comment]
Hi, there is a file in the project, Inorganic db.tsv in the thermo/Identifiers folder, that a new line needs to be added to as a correction, with the same format as the other lines.

There is no good way to add missing properties to thermo unfortunately at the moment.

**Comment by serge-suvorov** [comment]
Thank you
