### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dejac001** [CalebBell/thermo#44]
see line below: need to change *x_i* to *y_i*

https://github.com/CalebBell/thermo/blob/cba02552ea1a6947fcaa8407d4553e42e248e77c/thermo/eos_mix.py#L177

**Comment by dejac001** [comment]
below, need to change *log* to *ln* to be consistent

https://github.com/CalebBell/thermo/blob/cba02552ea1a6947fcaa8407d4553e42e248e77c/thermo/eos_mix.py#L481

**Comment by CalebBell** [comment]
Hi Robert,
Well spotted. I went out and did some searches throughout my code bases, there were probably 400ish references to log in formulas. Hopefully I got them all and now they are either ln or log_{10}. They will likely creep back in - many formulas come out of SymPy, which like all mathematical engines, considers log and ln to be the same. log10 is heretical!
Sincerely,
Caleb
