### ISSUE TITLE
Gas mixture properties

### ISSUE THREAD

**Issue by allanc1** [CalebBell/thermo#45]
Hi
I trying to work out how to calculate thermodynamic and transport properties of a gas mixture and am struggling to understand how to do this. The main properties required and h in kJ/kg, Cp in kJ/kgK, mu in Pa.s and k in W/m.K. Are you able to present an example?

Regards

**Comment by CalebBell** [comment]
Hi,

You can get them pretty easily:

```
from thermo import Mixture
m = Mixture(['nitrogen', 'oxygen'], zs=[.79, .21], T=500.0, P=101325.0) # T in K, P in Pa
print(m.H/1000, m.Cp/1000.0, m.mu, m.k) # Convert H, Cp Joules to kJ
(206.16723833116788, 1.0363227410784634, 2.69831536145733e-05, 0.03945449027992688)
```

Let me know if you have any trouble.

**Comment by allanc1** [comment]
Caleb

That is certainly straight forward. Your help is much appreciated. BTW, it appears that your enthalpy reference temperature is 288.15K. Please confirm

Allan

**Comment by CalebBell** [comment]
Hi Allan,
The reference conditions are 298.15K, 101325 Pa, whichever phase is present at those conditions, and with a reference enthalpy and entropy of zero. 

Sincerely,
Caleb

**Comment by allanc1** [comment]
Caleb
Thanks for that. I got confused, 288.15K is the ISA reference temperature for atmospheric studies while 298.15K is the standard temperature for the evaluation for calorific analyses.
