### ISSUE TITLE
Error in mixture properties

### ISSUE THREAD

**Issue by allanc1** [CalebBell/thermo#47]
Caleb
Your efforts in producing Thermo is much appreciated. However, it appears that there is an error in your method for calculating the properties of a gas mixture. If I use a mixture and N2 & H2O of 0.9 & 0.1 as mol fractions and a total pressure of 100kPa then I find that there a dramatic drop in enthalpy at approx. 100degC to a level which is somewhat higher than N2 only. Dalton's law of partial pressures says that water should start to condense at 45.8C. Further cooling would reduce the vapour fraction of H2O along the saturation line.

Kind regards
Allan

**Comment by CalebBell** [comment]
Hi Allan,
Please see the updated documentation on the new Flash and Phase classes:
https://thermo.readthedocs.io/thermo.flash.html

If you use the new way you shouldn't run into any more problems.

Sincerely,
Caleb

**Comment by allanc1** [comment]
CalebThanks for that, much appreciated.RegardsAllanOn 17/04/2021 2:19 pm, Caleb Bell ***@***.***> wrote:
Hi Allan,
Please see the updated documentation on the new Flash and Phase classes:
https://thermo.readthedocs.io/thermo.flash.html
If you use the new way you shouldn't run into any more problems.
Sincerely,
Caleb
