### ISSUE TITLE
Error calculating Joule-Thomson coef for mixture class

### ISSUE THREAD

**Issue by YifeiLu** [CalebBell/thermo#50]
Hello everyone, I've attempted to use thermo to do some calculation on gas mixtures. And apparently it does work correctly for the Mixture.JT. Even if I type in the example code, it still returns None, e.g. Mixture(['water'], ws=[1]).JT
Mixture(['dodecane'], ws=[1], T=400, P=1000).JTg.

**Comment by tedhyu** [comment]
Hi there:  I just made a new pull request to address this issue.  Hope it is helpful.

https://github.com/CalebBell/thermo/pull/51
