### ISSUE TITLE
Chemicals with IUPAC names "copper;iron;nickel" and "chromium;molybdenum;nickel" are in PubChem but give Exception: Chemical name not recognized

### ISSUE THREAD

**Issue by mcgeochd** [CalebBell/thermo#56]
link to copper;iron;nickel in PubChem is https://pubchem.ncbi.nlm.nih.gov/compound/121233900
link to chromium;molybdenum;nickel in PubChem is https://pubchem.ncbi.nlm.nih.gov/compound/57434369

the format is not the issue either because copper;nickel works fine

**Comment by CalebBell** [comment]
Hi,
The pubchem database is well and truly too big to be installed on your computer; only a small subset (~70000) with defined chemical structures and CAS numbers are included.. Neither of those chemicals, which are alloys anyhow, are in the database.
Cheers,
Caleb

**Comment by mcgeochd** [comment]
Thanks for the heads up, I don't suppose there's any other way I could use them in that case?

**Comment by CalebBell** [comment]
Issue #5 has a workaround you might find helpful.
