### ISSUE TITLE
Some solid materials appear to have no thermal conductivity, chemical.k = None

### ISSUE THREAD

**Issue by mcgeochd** [CalebBell/thermo#57]
Running this code for aluminium, copper, nickel, and iron returned None for all of them, but running it for oxygen, nitrogen, and carbon dioxide worked.

name = 'aluminium'
chem = ch.Chemical(name)
print ('{0} thermal conductivity: {1}'.format(name, chem.k))

**Comment by CalebBell** [comment]
Hi,
It would be nice if all chemicals had all data, but they simply don't. 
Caleb
