### ISSUE TITLE
[IDEA] Integrate with DWSIM

### ISSUE THREAD

**Issue by kookma** [CalebBell/thermo#58]
I think the thermo is a great tool and if it can integrate into Open-Source Process Simulator DWSIM https://github.com/DanWBR/dwsim6 it would be wonderful!

Note that DWSIM support Python!

**Comment by CalebBell** [comment]
Hi Dr. Rahmani,
I'm cleaning up the project and as this isn't really an issue or something actionable, I am closing this.
Daniel does incredible work and is an inspiration to every chemical engineer.
