### ISSUE TITLE
Enthaply and entropy for water

### ISSUE THREAD

**Issue by C-monC** [CalebBell/thermo#59]
Hello,

I am struggling to retrieve enthalpy and entropy for water at a specific temperature + pressure. The image below is an example of the values I want. 

![image](https://user-images.githubusercontent.com/17007879/91274872-a4cd4400-e77f-11ea-96d8-678f67780b3d.png)

Running the following code returns values that are different. Am I misunderstanding something?
```
from thermo.chemical import Chemical

w = Chemical('water')
w.calculate(T=300+273.15, P=300000)
print(w.H, w.S)
```
Returns
`2965116.5084832604 7339.656559980439`

**Comment by CalebBell** [comment]
Hi Simon,

Enthalpy and entropy are never absolute values, they have a reference point. Different steam tables use different reference points too although it is rarer. You can only compare differences between implementations. Thermo also does not have a steam table implementation at present so the values will not match perfectly. Thermo uses base SI units also so they are in J/kg and J/(kg*K).

Sincerely,
Caleb

**Comment by C-monC** [comment]
Thank you for the clarification.
