### ISSUE TITLE
Missing solid properties of normally gaseous elements

### ISSUE THREAD

**Issue by alexchandel** [CalebBell/thermo#63]
Hydrogen freezes at 13.99 K, oxygen at 54.36 K.  However, `thermo.chemical.Chemical('Hydrogen', 13).Vms` or `thermo.chemical.Chemical('Oxygen', 54).Vms` produce no values.

Although nonmetals have multiple solid allotropes, thermo could give properties for at least the lowest-pressure molecular solids, from correlations and more phase data.

**Comment by CalebBell** [comment]
Hi Alex,
Thanks for all of the bug reports. I have no problem including data along these lines, but is not on my radar at all. There is always plenty of work to do and I don't work with solids much.

**Comment by CalebBell** [comment]
Closing this issue as the above examples now provide a value. It is certainly not one I would recommend, but the extrapolation algorithms are now implemented. The calculation methodology is that of [Goodman](https://chemicals.readthedocs.io/chemicals.volume.html?highlight=Goodman#chemicals.volume.Goodman). This does not take into account the different solid phases whatsoever.
