### ISSUE TITLE
[bug] "bromine" resolves to wrong CAS

### ISSUE THREAD

**Issue by alexchandel** [CalebBell/thermo#64]
Bromine's critical point is 588 K, 10.34 MPa.  However the following returns `None` and `None`:
```py
import thermo
b = thermo.chemical.Chemical('Bromine')
b.Tc
b.Pc
```

This is because `Chemical('Bromine')` seems to resolve to [CAS 10097-32-2](https://www.chemeo.com/cid/29-188-2/Bromine), the bromine radical.  However the CAS number for dibromine is [7726-95-6](https://www.chemeo.com/cid/10-368-2/Bromine).

The problem even exists in thermo's periodic table:
```py
thermo.elements.element_list[35 - 1].CAS  # == '10097-32-2'
```

Please update this name resolution.

**Comment by CalebBell** [comment]
This data has migrated to the chemicals project, where the data has been fixed.
The fix is available in thermo through the development version.
