### ISSUE TITLE
[bug] 'arsenic' has wrong Tc

### ISSUE THREAD

**Issue by alexchandel** [CalebBell/thermo#65]
Arsenic (CAS 7440-38-2) has a [critical point](https://pubchem.ncbi.nlm.nih.gov/compound/Arsenic#section=Critical-Temperature-%26-Pressure) of 1673 K, 22.3 MPa.  However, thermo returns a Tc of 373 K:

```py
import thermo
thermo.chemical.Chemical('arsenic').Tc  # == 373
```

Please fix this.

**Comment by CalebBell** [comment]
This data has migrated to the [chemicals](https://chemicals.readthedocs.io/) project, where the data has been fixed.
The fix is available in thermo through the development version.
