### ISSUE TITLE
Mixture - isobaric expansion returns None

### ISSUE THREAD

**Issue by janstruzinski** [CalebBell/thermo#67]
Hi, 
Great job with thermo, I am really a great fan of this library - I have used it in quite a few projects by now. However, I recently run into an issue I cannot solve . Mixture.isobaric_expansion returns None. My Mixture is air, so it has single phase as written in the documentation, but has multiple species of gas. What could be an issue here? 
With regards,
Jan

**Comment by CalebBell** [comment]
Hi Jan,
The library is going through a redisign at the moment to provide a true N-phase flash which should also provide much more reliable properties (as well as fixing countless bugs like this).
Are you interested in trying it out? If so, you can install thermo from git and checkout the documents:

https://github.com/CalebBell/thermo/blob/master/docs/chemical_package_tutorial.rst
https://github.com/CalebBell/thermo/blob/master/docs/tutorial_phases_and_flash.rst
https://github.com/CalebBell/thermo/blob/master/thermo/phases.py

Sincerely,
Caleb

**Comment by janstruzinski** [comment]
Hi, 
Thanks for the quick answer! I will definitely take a look at it. 
With regards, 
Jan
