### ISSUE TITLE
Legality of sharing Perry's Databases

### ISSUE THREAD

**Issue by dejac001** [CalebBell/thermo#71]
Is it legal to copy data tables from Perry's chemical engineering handbook and redistribute them under an MIT license?

I know the book costs about $100-$200 bucks.

**Comment by CalebBell** [comment]
Hi Robert,

I am not a lawyer. The coefficients in Perry's are public; and they are developed by AICHE's [DIPPR](https://www.aiche.org/dippr), not Perry's publisher actually. As regressed coefficients are the result of a computer program and cannot be copyrighted, there is no issue. 

For the record, I would be happy to work with the DIPPR should they see an issue with this distribution. The data in Perry's is a tiny portion of their very impressive work. They are an incredible team and have written many excellent papers that have helped both me and Thermo!

Sincerely,
Caleb

**Comment by dejac001** [comment]
In order to be a secondary distributor of DIPPR, you need a license:
https://www.aiche.org/dippr/events-products/801-database/secondary-distributors

It looks like it costs at least $150 / year.

They say
"To become a secondary distributor, please contact us at dippr@aiche.org."

**Comment by CalebBell** [comment]
Hi Robert,
This is an open-source non-commercial project.
I don't have a relationship with the DIPPR, nor did I obtain these coefficients from them directly; we have no contractual relationship. 
Sincerely,
Caleb

**Comment by dejac001** [comment]
I realize that. I'm just saying that you should be careful.

I'd like to use these data tables too, but I'm going to email DIPPR and see if it's allowed first.

**Comment by yoelcortes** [comment]
@CalebBell, in the rare case you ever come by any issues with the use of data (like DIPPR) in your open-source projects, let me know and my lab group and institution will see how we can help.
