### ISSUE TITLE
[ASK] Enthalpy of Air 25°C at 60% humidity

### ISSUE THREAD

**Issue by vespadj** [CalebBell/thermo#80]
Hi!
Can you please provide an example for declare Air 25°C at 60% humidity?
I'm looking for a script to calculate enthalpy, indoor and outdoor.

indoor_air = Mixture(['air', 'water'], Vfls=[??, ??], T=273.15+25, P=1e5)
>>> indoor_air.Cp

Thanks

**Comment by CalebBell** [comment]
Hi vespadj,
I don't have any relative humidity functions written in thermo at the moment, although I do have highly accurate properties of dry air implemented.

Ian Bell's crazy amazing CoolProp has this functionality though! http://www.coolprop.org/fluid_properties/HumidAir.html#haprops-sample

Sincerely,
Caleb

**Comment by vespadj** [comment]
Thank you very much!
