### ISSUE TITLE
Where I can find the  binary interaction parameters

### ISSUE THREAD

**Issue by longcloud** [CalebBell/thermo#9]
Hi CalebBell,

Where is your binary interaction parameters databank, I just found this in your code, are they generated by the code? I know Aspen and ProII have a lot binary parameters, so just confused about this.

`      if kijs is None:   
            kijs = [[0]*self.N for i in range(self.N)]   
        self.kijs = kijs`

**Comment by CalebBell** [comment]
Hello longcloud,

Aspentech and SimSci are extremely large corporations with the resources to conduct comprehensive literature surveys or simply purchase their data. For example, I believe Aspentech licenses the complete VLE database from DDBST to perform regressions to obtain their binary interaction parameters.  DDBST has [1024504 data sets](http://ddbonline.ddbst.com/DDBSearch/onlineddboverview.exe?submit=Statistics) currently, and charges on the order of $35 USD per set. The multiplication of those values results in a very large number. 

You read the line correctly; kijs are assumed 0 unless specified by the user. For example, the H2S-CH4 system is known to have kij=0.08. To use that value, use:
```
>>> SRKMIX(T=190, P=40.53E5, Tcs=[373.2, 190.564], Pcs=[8936865.0, 4599000.0], omegas=[0.1, 0.008], zs=[ 0.07, 0.93], kijs=[[0, .08], [0.08, 0]])
<thermo.eos_mix.SRKMIX object at 0x7fe0e2f33590>
```

If you are aware of a large database of free VLE data, please let me know. The ones I am aware of are small and not critically evaluated:
* https://www.cheric.org/research/kdb/hcvle/hcvle.php
* http://vle-calc.com/index.html

Sincerely,
Caleb

**Comment by longcloud** [comment]
Hi Caleb,

Thanks for your replay, You made a fantastic library for chemical engineer. I worked at AspenTech in China. It would be pleasure if I can offer help to this library.

Thanks,
Cloud

**Comment by CalebBell** [comment]
Hello longcloud,

I appreciate the offer of help and the compliment. The following are all ways that you could contribute to thermo: 
* Find places the results from thermo don't seem right to you and submit bugs
* Find inputs that raise exceptions to thermo where they shouldn't
* Request features (It is useful to know what people are interested in, even if I can't make any promises about adding them)
* Write examples; for example performing some type of analysis on a chemical or mixture
* Find new sources of digital and reasonably licensed chemical data
* Promote thermo to engineers who might be interested in using Python

I would be very thankful if you looked into any of them.

Sincerely,
Caleb

**Comment by longcloud** [comment]
Hi Caleb,

I'm writing a web UI for your thermo, once it down, every engineer can use it without know python. And I assume they will ask more questions. I will show it to you.

Thanks,
Cloud

**Comment by longcloud** [comment]
Hi Caleb,

We made a web for thermo, the component and binary is not much. But we will improve it.
[
CalcPlayer](http://www.calcplayer.com)

Thanks,
Cloud

**Comment by sivarammurugan** [comment]
Hi Caleb,
First of all kudos to you   for this amazing package .  Regarding the binary interaction parameters , Chemsep has a a data bank , which includes the interaction parameters for sizable number of binary systems.  As I checked with Chemsep authors, these databanks  themselves are  released under following license terms http://www.perlfoundation.org/artistic_license_2_0.
So  we are free to use these data for this package. Could you consider adding these data to thermo, or if you are ok with it , I can create a pull request to upload these files.
Thanks 
Sivaram

**Comment by rmoreira00** [comment]
> Hello longcloud,
> 
> Aspentech and SimSci are extremely large corporations with the resources to conduct comprehensive literature surveys or simply purchase their data. For example, I believe Aspentech licenses the complete VLE database from DDBST to perform regressions to obtain their binary interaction parameters. DDBST has [1024504 data sets](http://ddbonline.ddbst.com/DDBSearch/onlineddboverview.exe?submit=Statistics) currently, and charges on the order of $35 USD per set. The multiplication of those values results in a very large number.
> 
> You read the line correctly; kijs are assumed 0 unless specified by the user. For example, the H2S-CH4 system is known to have kij=0.08. To use that value, use:
> 
> ```
> >>> SRKMIX(T=190, P=40.53E5, Tcs=[373.2, 190.564], Pcs=[8936865.0, 4599000.0], omegas=[0.1, 0.008], zs=[ 0.07, 0.93], kijs=[[0, .08], [0.08, 0]])
> <thermo.eos_mix.SRKMIX object at 0x7fe0e2f33590>
> ```
> 
> If you are aware of a large database of free VLE data, please let me know. The ones I am aware of are small and not critically evaluated:
> 
>     * https://www.cheric.org/research/kdb/hcvle/hcvle.php
> 
>     * http://vle-calc.com/index.html
> 
> 
> Sincerely,
> Caleb

Hi Caleb, 

Thank you very much for your work. From now on, I intend to give thermo a shot on my development of HVAC systems. I have been coding Cubic EoS myself for computing fluid mixture thermo. properties, but I rather try help on somebody else code and finish my HVAC modeling. 

Thus, I am posting some things that may be helpful to you.

Component database:
with VLE and NRTL parameters: Chemsep: http://chemsep.org/downloads/source.html
Another component database: https://www.chemeo.com/
Korean database: https://www.cheric.org/research/kdb/
for UNIFAC: http://www.ddbst.com/unifacga.html

MATLAB EoS routines including PC-SAFT, for instance: http://hpp.uva.es/open-source-software-eos/
Link for downloading the routines: https://drive.google.com/file/d/0B9uaKxwk5j7TTS1BR2lQcGZZOW8/view

Worth citing open source software almost as capable as Aspen Properties: DWSIM (http://dwsim.inforside.com.br/wiki/index.php?title=Main_Page)

Regards, 
Raul

**Comment by longcloud** [comment]
Hi, @CalebBell  and @rmoreira00 ,

Thanks for your information.
Do you have any paper about bk10, we find the original paper of Braun, but the calculation need search the nomogram when calculate logK=alfa log(K10) + log(beta), can you find the formula of alfa and beta?

Thanks a lot.
Cloud

**Comment by CalebBell** [comment]
Hi all,
There is a small sample database in the development version of thermo now, https://github.com/CalebBell/thermo/blob/master/thermo/interaction_parameters.py with data from [ChemSep](http://www.chemsep.org/).

Interaction parameters won't be loaded by default; it is left to the user to load them, or use their own, or a combination of the two.
You can see the variant.

I don't know much about bk10 but I suspect it is quite obsolete.

Sincerely,
Caleb
