### ISSUE TITLE
Invalid Method specified in T_dependent_property documentation

### ISSUE THREAD

**Issue by aakhtar8** [CalebBell/thermo#90]
In the documentation of T_dependent_property, and plotting section. ethanol_psat is plotted using **COOL_PROP**.
`ethanol_psat.plot_T_dependent_property(Tmin=400, Tmax=500, methods=['COOL_PROP', 'WAGNER_MCGARRY', 'DIPPR_PERRY_8E'], pts=30)`
during tests it shows no "No such method available". ethanol_psat.all_methods also doesn't list **COOL_PROP** as available method.
`>>> ethanol_psat.all_methods`
`{'EDALAT', 'LEE_KESLER_PSAT', 'VDI_TABULAR', 'WAGNER_MCGARRY', 'AMBROSE_WALTON', 'SANJARI', 'ANTOINE_POLING', 'DIPPR_PERRY_8E', 'WAGNER_POLING', 'BOILING_CRITICAL', 'VDI_PPDS'}`

either example should be updated, or the method validitiy should be checked

**Comment by CalebBell** [comment]
Hi,
The Coolprop method is from a third-party library, http://www.coolprop.org/
You will need to install it separately. 
Sincerely,
Caleb

**Comment by aakhtar8** [comment]
Hello, just to calrify, I wanted an update in thermo documentation so it
does not throw an error

**Comment by CalebBell** [comment]
Hi, I really don't understand what you are saying. The documentation runs fine on my machine, with CoolProp installed.
You can also install CoolProp and check that the documentation works. If you are in the root directory of this repository, and have pytest installed, you can run the doctests with:
pytest --doctest-glob='*.rst' docs

If you are not happy can you be more clear?
