### ISSUE TITLE
Is there a function to calculate the fugacity of each component in a multi-component mixture?

### ISSUE THREAD

**Issue by drLjc** [CalebBell/thermo#92]
Is there a function to calculate the fugacity of each component in a multi-component mixture?

**Comment by CalebBell** [comment]
Hi,

This is absolutely possible. Flash calculations use fugacities. The following code shows how to obtain fugacities in a binary mixture with the Peng-Robinson equation of state, for both a liquid and a gas phase.

```
from thermo import ChemicalConstantsPackage, PRMIX, CEOSLiquid, CEOSGas
constants, correlations = ChemicalConstantsPackage.from_IDs(['water', 'toluene'])
eos_kwargs = dict(Tcs=constants.Tcs, Pcs=constants.Pcs, omegas=constants.omegas)
liquid = CEOSLiquid(PRMIX, HeatCapacityGases=correlations.HeatCapacityGases, eos_kwargs=eos_kwargs)
gas = CEOSGas(PRMIX, HeatCapacityGases=correlations.HeatCapacityGases, eos_kwargs=eos_kwargs)

(liquid.to(T=300, P=1e4, zs=[.2, .8]).fugacities(), gas.to(T=300, P=1e4, zs=[.2, .8]).fugacities())

```
Sincerely,
Caleb

**Comment by drLjc** [comment]
Thank you very much for your reply. What I need to calculate is the fugacity of a component of a gas mixture. For example, a gas mixture of hydrogen, carbon monoxide, CO2 and water. I would like to obtain the fugacity of hydrogen.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CalebBell/thermo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月5日(星期天) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CalebBell/thermo] Is there a function to calculate the fugacity of each component in a multi-component mixture? (Issue #92)





 
Hi,
 
This is absolutely possible. Flash calculations use fugacities. The following code shows how to obtain fugacities in a binary mixture with the Peng-Robinson equation of state, for both a liquid and a gas phase.
 from thermo import ChemicalConstantsPackage, PRMIX, CEOSLiquid, CEOSGas constants, correlations = ChemicalConstantsPackage.from_IDs(['water', 'toluene']) eos_kwargs = dict(Tcs=constants.Tcs, Pcs=constants.Pcs, omegas=constants.omegas) liquid = CEOSLiquid(PRMIX, HeatCapacityGases=correlations.HeatCapacityGases, eos_kwargs=eos_kwargs) gas = CEOSGas(PRMIX, HeatCapacityGases=correlations.HeatCapacityGases, eos_kwargs=eos_kwargs) (liquid.to(T=300, P=1e4, zs=[.2, .8]).fugacities(), gas.to(T=300, P=1e4, zs=[.2, .8]).fugacities())  
Sincerely,
 Caleb
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CalebBell** [comment]
Hi,
You can change the component names and mole fractions and add more components in the above example. The fugacities returned are ordered in the same way as you enter the component names.
