### ISSUE TITLE
Neon density not evaluating

### ISSUE THREAD

**Issue by DanAtSuez** [CalebBell/thermo#96]
The following code returns no result:

`from thermo import *
from thermo.units import *
neon = Chemical('Neon', P=40*u.psi, T=u.Quantity('100 degF'))

neon.rho`

For any other chemical, this seems to work. Is there data missing on Neon, specifically?

**Comment by DanAtSuez** [comment]
Using a comment from another [(closed) issue](https://github.com/CalebBell/thermo/issues/89), I tried changing the gas molar volume method (Vmg) to 'TSONOPOLOUS_EXTENDED' and this generates rho. What would be the reason that the EOS Vmg method fails currently on Neon at ~standard conditions?

**Comment by CalebBell** [comment]
Hi Dan,
This behavior is no longer happening, so I am closing the issue. I honestly don't know when the fix made it in or what was it, but I have added a test for this set of inputs so I will know if this happens again!
Sincerely,
Caleb
