### ISSUE TITLE
Mixture properties differences in HCl and H2SO4 solution

### ISSUE THREAD

**Issue by dkchung22** [CalebBell/thermo#98]
Hi~ 
I found some differences in mixture properties in HCl and H2SO4 solution comparing with HTRI-VMG as follows:
I used Mixture module in thermo.

1) 7%-HCl in water: P=3kgf/cm2.G
2) 80%-H2SO4 in water: P=3.2kgf/cm2.G
I wonder what makes it so different and need help.

![image](https://user-images.githubusercontent.com/28613726/155307972-d132101d-3422-4443-8240-59dce381b7ca.png)

![image](https://user-images.githubusercontent.com/28613726/155308004-7d89189c-6546-4b0a-ab7e-644464710574.png)

**Comment by CalebBell** [comment]
Hi,
The results of thermo are available as-is.

**Comment by dkchung22** [comment]
Thanks, but, I need more understandings.
Do you mean the results of thermo is right or better than VMG ?
Differences in transportation properties are too big to adapt in fields.
Please some more detailed explanation.
